# CPack configuration for DASH Shell Windows
set(CPACK_PACKAGE_NAME "DASH")
set(CPACK_PACKAGE_VENDOR "DASH")
set(CPACK_PACKAGE_VERSION "0.5.13.5")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "13")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "POSIX-compliant Debian Almquist Shell for native Windows.")
set(CPACK_PACKAGE_HOMEPAGE_URL "http://gondor.apana.org.au/~herbert/dash/")
set(CPACK_PACKAGE_CONTACT "Samuel Marks")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "DASH")
set(CPACK_GENERATOR "ZIP;NSIS")

# NSIS Settings
set(CPACK_NSIS_DISPLAY_NAME "DASH Shell")
set(CPACK_NSIS_PACKAGE_NAME "DASH Shell")
set(CPACK_NSIS_MODIFY_PATH ON)
